- ohkami/Cargo.toml
- ohkami/src/layer0_lib/status.rs
- ohkami/src/layer1_req_res/response/into_response.rs
- ohkami/src/layer4_router/mod.rs
- ohkami/src/layer4_router/radix.rs
- ohkami/src/layer4_router/trie.rs
- Fix trie: make be able to parallel registeration of param and static patterns
- Fix radix: `split_next_section` to return `remaining` that **starts with `/`** if `path` contains `/`
> Fix router 2023 01 07

- README.md
Fix:
```diff
- $ curl http://localhost:3000/hc
+ $ curl http://localhost:3000/healthz
$ curl http://localhost:3000/hello/your_name
Hello, your_name!
```
> Fix: curl path in quick start

- ohkami/src/layer1_req_res/request/mod.rs
- ohkami/src/layer1_req_res/request/path.rs
- ohkami/src/layer3_router/radix.rs
- Add a comment describing why it's ok to force-strip trailing `/` in request path even if raw path was just `/`
- Fix: `Request::path(&self)` to show user `/` if internal path bytes is `` (empty, e.t. the original request path was `/`)
> Fix: `Request::path(&self)`: show `/` to user if internal path bytes is `` (empty)

- README.md
- examples/Cargo.toml
- examples/form/Cargo.toml
- examples/form/src/main.rs
- examples/hello/Cargo.toml
- examples/hello/src/main.rs
- examples/quick_start/src/main.rs
- ohkami/Cargo.toml
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/mod.rs
- ohkami/src/handler/handlers.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/howl.rs
- ohkami/src/ohkami/router/radix.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/request/from_request.rs
- ohkami/src/request/method.rs
- ohkami/src/request/mod.rs
- ohkami/src/request/store.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/into_response.rs
- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
- ohkami/src/utils/now.rs
- Fix to include serde with `derive` feature
- And fix `examples` workspace to use ohkami with `default-features = false` to always emit `DEBUG` feature
- Implement correct connection handling required in HTTP/1.1
- Fix `Fang` registeration to assure that duplicated (same) fangs are merged to one
- Improve error messages or some things for developers
- Update docs
> Fix around request handling

- ohkami/Cargo.toml
- ohkami/src/handler/into_handler.rs
- ohkami/src/ohkami/router/_test.rs
- ohkami/src/ohkami/router/radix.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/request/from_request.rs
- ohkami/src/testing/mod.rs
- ohkami_lib/Cargo.toml
Now `Ohkami`'s routing depend on registration order :
```rs
let o = Ohkami::new((
"/hello/:name".GET(hello),
"/hello/help" .GET(hello_help),
));
```
Here we expect `GET /hello/help` is handled by `hello_help` of course, but actually done by `hello` ( and returns `hello, help` ! )
This is because the router performs route-matching just in order where they're registered, then any GET request to `/hello/*` matches to `hello/:name` and handled by `hello`.
This PR resolves this problem by sorting every children nodes of `TrieRouter` just before it is transformed to `RadixRouter` in order `static < param`.
_NOTE_: additionally fixed a bug found when adding a test for the sorting: unnecessary percent-decoding of request path.
> Update router sort children by pattern

- Taskfile.yaml
- benches/Cargo.toml
- benches/benches/request_headers.rs
- benches/benches/response_headers.rs
- benches/src/bin/hello.rs
- benches/src/response_headers/heap_ohkami_headers.rs
- benches/src/response_headers/heap_ohkami_headers_nosize.rs
- ohkami/Cargo.toml
- ohkami/src/request/_test_parse.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
- Put in `Box<_>` and rename
- `Request.{ __metadata => __buf__ }`
- `Request.headers.{ values => standard }`
- `Response.headers.{ values => standard }`
- Remove `LOOP_LIMIT` in `Session::manage`, just `loop` instead
- ( Add `benches/src/bin/hello` and, on my PC, impl the same bench app in axum, and defeated it in various conditions ! )
> More correct and efficient req res

- examples/hello/src/main.rs
- ohkami_macros/src/query.rs
Support struct-level `#[query]` attribute like
```rust
#[Query]
#[query(deny_unknown_fields)]
struct HelloQuery<'q> {
name: &str,
repeat: Option<usize>,
}
```
( by correctly process into serde container attributes )
> Support struct-level #[query] attributes

- examples/form/src/main.rs
- examples/hello/src/main.rs
- ohkami/src/builtin/fang/jwt.rs
- ohkami/src/builtin/fang/timeout.rs
- ohkami/src/fangs/handler/into_handler.rs
- ohkami/src/request/from_request.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/into_response.rs
- ohkami/src/response/mod.rs
- ohkami/src/typed/status.rs
- ohkami_macros/src/query.rs
For more consistent names, and, some fangs like HTML layout fang:
```rs
struct LayoutFang;
impl FangAction for LayoutFang {
async fn back<'b>(&'b self, res: &'b mut Response) {
if res.headers.ContentType().is_some_and(|ct| ct.starts_with("text/html")) {
let inner = res.drop_content();
res.set_html(some_layout_fn(inner));
}
}
}
```
> Rebuild `Response`'s public methods

- ohkami/src/lib.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/_test_headers.rs
- ohkami/src/response/headers.rs
- Update `RequestHeaders::Cookie`: return iterator of (name, value)
- Add `header::private::{SetCookie, SetCookieBuilder}` and use them from `ResponseHeaders`
> Fix Cookie handling

- benches/src/bin/sleep.rs
- ohkami/Cargo.toml
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/from_request.rs
- ohkami/src/session/mod.rs
- Update `Session::manage` to shutdown each connection by 42 secs
- Add description of it to `Ohkami::howl` doc
- Add `benches/sleep`
( TODO: make hardcoded "42 secs" configureable )
> Add Keep-Alive timeout

- ohkami/Cargo.toml
- ohkami/src/builtin/fang/cors.rs
- ohkami/src/response/headers.rs
- ohkami/src/testing/mod.rs
Add tests for builtin CORS fang and fix wrong behaviors
> Fix CORS & `testing::TestResponse::header`

- ohkami_macros/Cargo.toml
- ohkami_macros/src/worker.rs
Search workspace members' wrangler.tomls if wrangler.toml is not found in project root
> Partially support cargo workspace in `#[bindings]`

- examples/hello/src/main.rs
- ohkami/src/typed/payload.rs
- ohkami_macros/src/payload.rs
instead of a validating method itself
> `#[Payload]`:  take validating expression(s) in `where 〜`

- ohkami/src/builtin/fang/cors.rs
- ohkami/src/fangs/handler/into_handler.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/build.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/request/from_request.rs
- ohkami/src/request/memory.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
- ohkami/src/typed/payload.rs
- ohkami/src/typed/status.rs
- Change `Payload + Deserialize`'s `FromRequest::from_request`: respond with error text
- Update internal error logging to call `worker::console_error` additionally on `rt_worker`, instead of only `eprintln`
> Improve error reportings

- ohkami/src/builtin/fang/cors.rs
- ohkami/src/fangs/handler/into_handler.rs
- ohkami/src/ohkami/build.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/request/from_request.rs
- ohkami/src/request/memory.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/headers.rs
- ohkami/src/session/mod.rs
- ohkami/src/typed/payload.rs
- ohkami/src/typed/status.rs
omit `use crate::warning` and call `crate::warning!(〜)` directly to avoid rustc warnings
> Call `crate::warning!` directly

- ohkami/src/response/mod.rs
- ohkami_lib/src/lib.rs
- ohkami_lib/src/num.rs
- Implemented `ohkami_lib::num::hexize` and use it in `Content::Stream` arm of `Response::send`
> Optimized size-hexizing in sending chunked encoding

- ohkami/src/lib.rs
instead of `-> impl Stream<...>`.
This is for applying auto-impl traits, like `Send`, for returned types.
> Return concrete type within all methods of `utils::StreamExt`

- ohkami/Cargo.toml
- ohkami/src/builtin/fang/cors.rs
- ohkami/src/builtin/fang/timeout.rs
- ohkami/src/fangs/handler/mod.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/router/radix.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/testing/mod.rs
- Stop sticking to respond with `405 Method Not Allowed` and use `404 Not Found` instead in following situation :
```rust
Ohkami::new(
"/abc".POST( 〜 )
).howl("localhost:3000").await
```
```
curl http://localhost:3000
```
- Respond with `501 Not Implemented` for OPTIONS requests to existing paths by default
- Fix HEAD handling to remain `Content-Type` header from GET response
> Dispatch routers by method

- ohkami/src/ohkami/router/radix.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/request/_test_parse.rs
- ohkami/src/request/mod.rs
- ohkami/src/request/path.rs
- Save memory for redundant `HEAD` tree
- FIx `request::Path::as_ref` to return `"/"` when the original path was `"/"` & add test for it
> handle HEAD request by GET tree and respond without content, Content-Length

- examples/Cargo.toml
- examples/basic_auth/Cargo.toml
- examples/basic_auth/src/main.rs
- ohkami/src/builtin/fang.rs
- ohkami/src/builtin/fang/basicauth.rs
- ohkami/src/builtin/fang/jwt.rs
- ohkami/src/response/headers.rs
- Add `builtin::fang::BasicAuth`
- Add `examples/basic_auth`
> Builtin basic auth fang

- README.md
- benches/Cargo.toml
- examples/Cargo.toml
- ohkami/Cargo.toml
- ohkami_macros/Cargo.toml
- ohkami_macros/src/worker.rs
Before
```toml
[vars]
VAR = "value"
```
```rust
#[bindings]
struct Bindings;
```
had method `Bindings::VAR() -> &'static str`, but it's more natural to have const `Bindings::VAR: &'static str`
---
This is a breaking change and bumps major version
> `#[bindings]` : variable bindings as associated consts

- benches/.gitignore
- benches/Cargo.toml
- benches/benches/imf_fixdate.rs
- ohkami/Cargo.toml
- ohkami/src/lib.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/mod.rs
- ohkami/src/request/path.rs
- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
- ohkami_lib/Cargo.toml
- ohkami_lib/src/lib.rs
- ohkami_lib/src/slice.rs
- ohkami_lib/src/time.rs
( as far as I know `async-std` doesn't provide `split` functionaluty like `tokio`'s one )
> use `TcpStream::split` in `Session::manage` on `rt_tokio` & omit `Vec` from `Path.params`

- ohkami/src/lib.rs
- ohkami/src/session/mod.rs
Before ohkami uses 42 secs for Keep-Alive timeout. This PR makes this configurable by environment variable `OHKAMI_KEEPALIVE_TIMEOUT` and default to 42 secs.
> feat: set keep-alive timeout by environment variable

- benches/benches/atoi.rs
- benches/src/lib.rs
- benches/src/light_ohkami.rs
- ohkami/src/request/headers.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/_test_headers.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
- ohkami_lib/src/num.rs
1. Introduce `ohkami::lib::num::atoi` to serialize content lengths faster, at least, than `usize::to_string`.
- benchmark is in `benches/benches/atoi.rs`
- more optimization is welcome
---
3. Before ohkami uses `Box<[{clone on write buffer}; {number of req/res headers}]>` to have standard header values, but this is *quite heavy to initialize on each request handling*. So this PR alters it like
```rust
struct Standard {
index:  [u8; {number of req/res headers}],
values: Vec<{clone on write buffer}>
}
impl Standard {
fn new() -> Self {
Self {
index:  [{invlid index}; {number of req/res headers}],
values: Vec::with_capacity( {number of req/res headers} / 4 )
}
}
}
```
for lightweight initialization without performance degradation.
- initial capacity `{number of req/res headers} / 4` is …
> perf: lightweight headers map

- benches/benches/itoa.rs
- ohkami_lib/src/num.rs
This also makes `itoa` slightly more optimised for `#[cfg(target_pointer_width = "16")]` targets, as `usize::MAX` is used to "stop unrolling" now - specifically, to generate `if` conditions which are known to be always-false at compile time.
Benchmarking shows that this is on par with the previous `itoa`:
```
running 8 tests
test itoa_01   ... bench:       5,182.50 ns/iter (+/- 326.24)
test itoa_02   ... bench:       3,865.63 ns/iter (+/- 38.90)
test itoa_03   ... bench:       3,719.65 ns/iter (+/- 132.43)
test itoa_04   ... bench:       9,563.68 ns/iter (+/- 173.80)
test itoa_05   ... bench:       3,206.98 ns/iter (+/- 104.76)
test itoa_06   ... bench:          75.10 ns/iter (+/- 1.69)
test itoa_07   ... bench:          75.02 ns/iter (+/- 1.52)
test to_string ... bench:       6,197.77 …
```
> Unroll `itoa` with a macro

- benches/Cargo.toml
- benches/benches/itoa.rs
The current benchmark did not return the generated values to the bencher, so optimization could be done assuming that the values are not returned. Also, only very few digits are benchmarked.
```
running 9 tests
test itoa_01        ... bench:   1,182,800.00 ns/iter (+/- 75,023.00)
test itoa_02        ... bench:   1,179,170.00 ns/iter (+/- 348,201.00)
test itoa_03        ... bench:   1,097,655.00 ns/iter (+/- 87,127.25)
test itoa_04        ... bench:   1,104,555.00 ns/iter (+/- 99,388.50)
test itoa_05        ... bench:   1,220,075.00 ns/iter (+/- 76,315.00)
test itoa_06        ... bench:     933,513.75 ns/iter (+/- 38,577.38)
test itoa_07        ... bench:     866,740.00 ns/iter (+/- 64,357.00)
test itoa_lib       ... bench:     853,720.00 ns/iter (+/- 59,496.00)
test itoa_to_string ... …
```
> Using random values in the `itoa` benchmark

- benches/benches/itoa.rs
> Wrong output `itoa_03` and `itoa_04`

- .github/workflows/auto_approve.yml
- benches/benches/itoa.rs
- Now `itoa` is only used for serializing `Content-Length`
- In most cases, a single, non-streaming HTTP response will have Content-Length of less than 10GB
> refactor: bench `itoa` with test cases of less than 10GB

- benches/benches/itoa.rs
- ohkami_lib/src/num.rs
In current `itoa`, `unroll!` arguments is just a sequence of 1 ~ 19 :
```
unroll!(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19);
```
However, it is not explicitly clear from this code why providing up to 19 is correct.
So this adds static assertion
```rust
#[cfg(target_pointer_width = "64")]
const _/* static assert */: [(); 19] = [(); MAX];
```
to describe it.
> `itoa`: statically assert that the max of `MAX` is 19

- benches/benches/itoa.rs
- Fix `itoa_03` and remove `itoa_04` due to its fundamentally wrong logic
- Refactor `benchmark!` to perform 3-level benchmarks
> refactor: bench itoa in 3 levels

- ohkami/Cargo.toml
- ohkami/src/header/map.rs
- ohkami/src/header/mod.rs
- ohkami/src/request/headers.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/_test_headers.rs
- ohkami/src/response/headers.rs
Before `response::Headers::write` iterates all standard response header and check if the response has each of them every time.
This PR fix it to just iterate once-inserted standard headers and skip already-removed ones
> refactor standard headers: iterate only by inserted values

- benches/benches/itoa.rs
- Instead of allocating a string area for each integer, write directly to a buffer and output.
- Generate 4-digit integers in advance, paste them together, and output.
```
$ cargo +nightly bench --package ohkami_benches --bench itoa
running 76 tests
test a_small_http_response_content_length::itoa_01                      ... bench:     144,725.37 ns/iter (+/- 2,149.23)
test a_small_http_response_content_length::itoa_02                      ... bench:     123,626.23 ns/iter (+/- 472.58)
test a_small_http_response_content_length::itoa_03                      ... bench:     133,868.24 ns/iter (+/- 452.17)
test a_small_http_response_content_length::itoa_05                      ... bench:      95,705.51 ns/iter (+/- 85.25)
test a_small_http_response_content_length::itoa_06 …
```
> `itoa`: Can be about 10 times faster

- benches/Cargo.toml
- benches/benches/request_headers.rs
- benches/benches/response_headers.rs
- benches/src/header_hashbrown.rs
- benches/src/response_headers/fxmap.rs
- ohkami/src/response/headers.rs
Fix `response::Headers::_write_to`, for-benchmark wrapper of `write_unchecked_to`, to reserve `buf` capacity by `Vec::reserve` instead of `Vec::reserve_exact`. Benchmark examples:
before
```txt
test write_02_http_crate       ... bench:         118.08 ns/iter (+/- 21.05)
test write_03_fxmap            ... bench:          94.93 ns/iter (+/- 5.96)
test write_03_header_hashbrown ... bench:          94.41 ns/iter (+/- 7.58)
test write_03_ohkami           ... bench:         153.62 ns/iter (+/- 12.09)
test write_04_headermap        ... bench:         105.58 ns/iter (+/- 18.24)
```
after
```txt
test write_02_http_crate       ... bench:         116.04 ns/iter (+/- 2.89)
test write_03_fxmap            ... bench:         100.20 ns/iter (+/- 4.12)
test write_03_header_hashbrown ... bench: …
```
> fix headers bench: use `Vec::reserve` for reserve buf capacity

- ohkami_lib/src/time.rs
because IMF-fixdate ( HTTP datetime format ) doesn't require the fraction of seconds
> Remove `frac` from `time::Time`

- README.md
- ohkami/src/lib.rs
- ohkami/src/session/mod.rs
- ohkami/src/ws/frame.rs
- ohkami/src/ws/mod.rs
- ohkami/src/ws/session.rs
Add `crate::env::OHKAMI_WEBSOCKET_TIMEOUT` with default 1 hour for resource protection
> feat: OHKAMI_WEBSOCKET_TIMEOUT

- examples/websocket/src/main.rs
- examples/websocket/template/index.html
- ohkami/src/lib.rs
- ohkami/src/session/mod.rs
- ohkami/src/ws/session.rs
Before sended one only when aborting by `OHKAMI_WEBSOCKET_TIMEOUT`, otherwise just shutdowned, which is not a desired behavior. 
This fixes to send close frame in any case.
> fix: always send close frame when closing websocket connection

- README.md
- ohkami_lib/src/stream.rs
`q.add(value)`: shorthand for `q.push(Ok(value))`, which was almost a boilerplate in use of `stream::queue`
> feat: `q.add` in `stream::queue`

- examples/static_files/src/main.rs
- ohkami/src/ohkami/build.rs
specialize access to `Dir/path/index.html` to
normal :
omit `.html` :
> feat: always specialize `index.html` in `.Dir`

- examples/websocket/src/main.rs
- examples/websocket/template/index.html
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/router/radix.rs
- ohkami/src/ohkami/router/trie.rs
- ohkami/src/ws/mod.rs
- fix routing bug and add test:
Before `GET /abcd` to
```rust
Ohkami::new((
"/abc".GET(|| async {"This is abc"}),
"/abcd".GET(|| async {"This is abcd"}),
))
```
results to NotFound because this matches to `/abc`. So This PR fixes to sort this pattern of routing to
```rust
Ohkami::new((
"/abcd".GET(|| async {"This is abcd"}),
"/abc".GET(|| async {"This is abc"}),
))
```
in ahead.
---
- fix ws handler `Fn` to `FnOnce`
Before the handler was `Fn`. So, user-defined WebSocket response **holding some data** like
```rust
struct MyWebSocket<'ws> {
ctx: WebSocketContext<'ws>,
user_name: String, // <-- data
}
async fn handler(
ctx: WebSocketContext<'_>,
user_name: String
) -> MyWebSocket<'_> {
MyWebSocket { ctx, user_name }
}
```
**must** implement `IntoResponse` as
```rust
impl IntoResponse for …
```
> fix ws Handler: `Fn` -> `FnOnce` & routing bug

- examples/websocket/src/main.rs
- examples/websocket/template/index.html
- ohkami/src/session/mod.rs
- ohkami/src/ws/connection.rs
- ohkami/src/ws/message.rs
- ohkami/src/ws/mod.rs
Before `ws::Connection` used just `*mut Conn` in its internal, but this easily cause **_undefined behavior_** if user spawns detouched tasks ( tasks that was spawned but not joined/awaited ) in WebSocket handler.
In addition, easy supporting such use, just avoiding UB, is not enough to avoid a **_resource leak_** due to something like infinite loop or dead lock in a WebSocket handler ( WebSocket handler without detouched tasks is protected by automatically timeout by `OHKAMI_WEBSOCKET_TIMEOUT` ).
This PR:
- introduce `State { Alive, Closed }` in `ws::Connection` and make it `Closed` when sending `Message::Close`
- use `Arc` instead of a raw pointer
which enables to **_validate the state_** to be `Alive` before `{recv, send, write, flush, split}` and make accessing to `ws::Connection` in a …
> Explicitly not-support using `ws::Connection` in detouched tasks

- README.md
- Taskfile.yaml
- ohkami/Cargo.toml
- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/ohkami/router/radix.rs
- ohkami_lib/src/serde_urlencoded/_test.rs
Support graceful shutdown by `graceful` feature on `rt_tokio` ( `graceful` on other runtimes is a future goal )
> feat: Graceful Shutdown

- benches/Cargo.toml
- ohkami/src/ohkami/mod.rs
- drop listener just when `ctrl_c_tx.closed()` in order to deny, not only not-handle, further connections
- more readable code
> refactor: graceful shutdown impl

- ohkami/src/lib.rs
`compile_error!` under a `cfg` in an anon-const under another `cfg` :
```rust
#[cfg(not(feature="DEBUG"))] const _: () = {
#[cfg(all(feature="rt_worker", not(target_arch="wasm32")))]
compile_error! {"
`rt_worker` must be activated on `wasm32` target!
(We recommend to touch `.cargo/config.toml`: `[build] target = \"wasm32-unknown-unknown\"`)
"}
};
```
is unexpectedly displayed as an error on ( at least ) VSCode, which is not an actual problem but somehow annoying.
This PR fixes it not to use the anon-const and flatten `cfg`s.
- before
- after
> chore: not combine `cfg`s between outer and inner an anon-const to avoid error message on editor

- ohkami/src/lib.rs
- specify crate version in `html_root_url`
- sync crate inner doc commet with the initial part of README
> chore:  fix `html_root_url` & crate inner doc comment

- ohkami/src/header/map.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/memory.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
Before `Session` created one pair of `Request`/`Response` for each incoming request, this means it performs `Drop` and initialization 2N times.
This PR changes this into initialize `Request` only once per one `Session` and clear & reuse it through one session.
```sh
cargo run --bin param --no-default-features --release
```
```sh
wrk -H 'Connection: keep-alive' --connections 32 --threads 16 --duration 3s --timeout 1s 'http://localhost:3000/user/1234567890987654321'
```
Requests/sec
|   |  before   |   after   |
|---|-----------|-----------|
| 1 | 705338.20 | 717771.62 |
| 2 | 709623.03 | 715556.64 |
| 3 | 705485.43 | 724493.01 |
> perf: reuse `Request` in a session

- README.md
- Taskfile.yaml
- examples/Cargo.toml
- examples/hello/src/main.rs
- ohkami/Cargo.toml
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/_test_parse.rs
- ohkami/src/request/mod.rs
- ohkami/src/session/mod.rs
- ohkami/src/testing/mod.rs
Get remote peer's IP address in `Ohkami::howl`, pass it to `Session::manage`, and set `Request`'s `addr` public field to it when `init`.
This PR doesn't support `"ip"` on `"rt_worker"`.
references:
- https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-connecting-ip
- https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips
> feat: Add `"ip"` feature

- Cargo.toml
- README.md
- Taskfile.yaml
- benches_smol/Cargo.toml
- benches_smol/src/bin/param.rs
- ohkami/Cargo.toml
- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/ws/connection.rs
closes https://github.com/ohkami-rs/ohkami/issues/242
---
> A small and fast async runtime for Rust
https://github.com/smol-rs/smol
> feat: add `"rt_smol"`

- ohkami/src/format/builtin.rs
- ohkami/src/format/builtin/html.rs
- ohkami/src/format/builtin/json.rs
- ohkami/src/format/builtin/multipart.rs
- ohkami/src/format/builtin/query.rs
- ohkami/src/format/builtin/text.rs
- ohkami/src/format/builtin/urlencoded.rs
- ohkami/src/format/mod.rs
We published [SerdeV](https://github.com/ohkami-rs/serdev) and it's enough to perform validation on deserializing (if needed).
> chore: remove format::V

- benches_rt/.gitignore
- benches_rt/tokio/src/bin/param.rs
I found that in very simple senario, like getting a path param and echoing it as text, the higher setting `event_interval` of tokio runtime, the lower the performance be.
So this PR tries setting it to the minimum value, 1, in `benches_rt/tokio/src/bin/param` ( default: 61 ).
ref: https://docs.rs/tokio/1.39.3/tokio/runtime/struct.Builder.html#method.event_interval
```sh
wrk -H 'Connection: keep-alive' --connections 32 --threads 16 --duration 3s --timeout 1s 'http://localhost:3000/user/1234567890987654321'
```
- default ( `#[tokio::main] async fn main()` )
1.  Requests/sec: 725217.89
2. Requests/sec: 726961.24
3. Requests/sec: 724529.73
- set `event_interval` to 1 ( `.event_interval(1)` )
1. Requests/sec: 874318.85
2. Requests/sec: 865562.96
3. Requests/sec: 848599.67
> chore: benches_rt/tokio: set `event_interval` to 1

- ohkami/Cargo.toml
> chore: dependencies: remove tokio's "sync" feature ( unused )

- ohkami/Cargo.toml
- ohkami/src/ws/worker.rs
In `ws::SessionMap` on `rt_worker`,
- use `Vec::swap_remove` in `remove` instead of `Vec::remove` ( here not needed to preserve ordering of the remaining elements )
- omit redundant `None` check in `get`, `get_mut`
> perf(ws on rt_worker): `SessionMap`: use `swap_remove` & omit redundant `None` check

- ohkami/Cargo.toml
- ohkami/src/request/headers.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
Support
```rust
{req/res}.headers.set()
.Header(if cond {Some("value".into())} else {None})
```
`Some()` can only hold direct `Cow<'static, str>` for `None` convention ( if this is generic, `.set().Header(None)` to remove is to *need type annotation* )
> enhance: headers set optional value

- ohkami/Cargo.toml
- ohkami/src/header/map.rs
- ohkami/src/header/mod.rs
- ohkami/src/request/headers.rs
- ohkami/src/response/headers.rs
replace custom headers store with
```rust
/// Key-Value map mainly used to store custom headers.
/// 
/// Usually, a web app handles 0 ~ 4 custom headers, and so
/// simple `Vec<(K, V)>` is efficient than `HashMap<K, V>`
/// to store/iterate/mutate.
pub(crate) struct TupleMap<K: PartialEq, V>(
Vec<(K, V)>
);
```
> perf: custom headers: use `Vec<(K, V)>` instead of `FxHashMap<K, V>`

- ohkami/src/header/map.rs
- ohkami/src/request/_test_headers.rs
- ohkami/src/request/headers.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/_test_headers.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
- ohkami/src/testing/mod.rs
> rename(headers): set `.custom()` -> `.__()` / get `.custom()` -> `.get()`

- benches_rt/glommio/Cargo.toml
- benches_rt/smol/Cargo.toml
- benches_rt/tokio/Cargo.toml
- ohkami/Cargo.toml
- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/mod.rs
- ohkami/src/router/final.rs
- ohkami_lib/src/lib.rs
- ohkami_lib/src/signal.rs
closes #285
---
refactor codes around runtime-abstraction, with fixing https://github.com/ohkami-rs/ohkami/issues/285 and add a regression test ( `ohkami::can_howl_on_any_native_runtime` test )
> refactor: runtime abstraction

- Cargo.toml
- README.md
- Taskfile.yaml
- benches_rt/nio/Cargo.toml
- benches_rt/nio/src/bin/param.rs
- ohkami/Cargo.toml
- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
close #286 
---
suport [nio](https://github.com/nurmohammed840/nio) with updates of tests, docs, CI
> feat: support `nio` async runtime

- Taskfile.yaml
- examples/Cargo.toml
- ohkami/Cargo.toml
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/builtin/timeout.rs
- ohkami/src/fang/middleware/util.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/_test_extract.rs
- ohkami/src/request/_test_headers.rs
- ohkami/src/request/mod.rs
- ohkami/src/testing/mod.rs
- This simplifies the design of feature flags.
- `testing` module is automatically excluded in release build ( no one will like to opt out this behavior ).
> chore: remove feature flag `testing` && export `testing` module behind `#[cfg(debug_assertions)]`

- ohkami/Cargo.toml
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/builtin/timeout.rs
- ohkami/src/fang/middleware/util.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/_test_extract.rs
- ohkami/src/request/_test_parse.rs
- ohkami/src/response/_test.rs
- refactor interruption handling not to use `select!` macro ( by implementing and replacing to `CtrlC::until_interrupt` )
- this enables more cleaning up dependencies and feature flags
- and doesn't cause performance degradation
> refactor: remove select macro of handling interrupt

- ohkami/src/ohkami/mod.rs
- ohkami/src/ws/mod.rs
- `OHKAMI_KEEPALIVE_TIMEOUT` ( secs; default: 42 )
- `OHKAMI_WEBSOCKET_TIMEOUT` ( secs; default: 3600 )
> docs: update doc comment for current `OHKAMI_*` environment variables

- README.md
- examples/basic_auth/src/main.rs
- examples/chatgpt/src/main.rs
- examples/form/src/main.rs
- examples/hello/src/main.rs
- examples/websocket/src/main.rs
- ohkami/src/fang/builtin/basicauth.rs
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/builtin/memory.rs
- ohkami/src/fang/builtin/timeout.rs
- ohkami/src/fang/middleware/util.rs
- ohkami/src/header/append.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/ohkami/routing.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/mod.rs
- ohkami/src/router/base.rs
- samples/petstore/src/main.rs
- samples/realworld/src/handlers.rs
- samples/realworld/src/handlers/profiles.rs
- samples/realworld/src/handlers/user.rs
- samples/worker-with-openapi/src/lib.rs
This PR enables to pass fangs via `Ohkami::new`:
```rust
Ohkami::new((
Logger,
Memory::new(connection_pool),
"/users"
.GET(list_users)
.POST(create_user),
))
```
This is the same as
```rust
Ohkami::with((
Logger,
Memory::new(connection_pool)
), (
"/users"
.GET(list_users)
.POST(create_user),
))
```
but the former may be somehow more unified and simple.
> feat: pass fangs via `Ohkami::new`

- README.md
- benches/benches/tuplemap_vs_hashmap.rs
- examples/chatgpt/src/main.rs
- ohkami/src/fang/builtin.rs
- ohkami/src/fang/builtin/context.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/header/map.rs
- ohkami/src/header/mod.rs
- ohkami/src/lib.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/store.rs
- ohkami/src/response/headers.rs
- ohkami_lib/src/lib.rs
- ohkami_lib/src/map.rs
- samples/petstore/src/main.rs
- samples/realworld/src/handlers.rs
- samples/realworld/src/handlers/articles.rs
- samples/realworld/src/handlers/profiles.rs
- samples/realworld/src/handlers/tags.rs
- samples/realworld/src/handlers/user.rs
- samples/realworld/src/handlers/users.rs
- samples/worker-with-openapi/src/lib.rs
This PR replaces `fang::Memory` into `fang::Context`. The user-interface does not change except for renaming itself, but internal implementation of `Request`'s store is updated to use `ohkami_lib::TupleMap` ( instead of `HashMap<_, _, BuildHasherDefault<TypeIdHasher>>` ) .
As the benchmark ( at benches/benches/tuplemap_vs_hashmap.rs; designed with most-used sizes of the store in mind ) shows, `HashMap<_, _, BuildHasherDefault<AsIsHasher>>` ( `AsIsHasher` is the same as `TypeIdHasher` ) is performant in same-level or somehow faster than `TupleMap` **at searching**, but **slower at creation ( initializing + extendings )** by a little larger differences than searching's one in most cases.
<details>
<summary>column</summary>
In this case, the `AsIsHasher` ( or TypeIdHasher ) makes a quite …
> `Memory` to `Context`

- ohkami/src/lib.rs
rust-analyzer seems to avoid rendering `<a><img /></a>`s
> chore: remove badges from lib.rs doc

- Taskfile.yaml
- ohkami/Cargo.toml
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/handler/mod.rs
- ohkami/src/ohkami/routing.rs
- ohkami/src/response/into_response.rs
- ohkami/src/sse/mod.rs
- ohkami/src/typed/status.rs
- ohkami/src/util.rs
- ohkami/src/ws/native.rs
- ohkami/src/ws/worker.rs
- ohkami_openapi/src/_test.rs
- ohkami_openapi/src/lib.rs
- ohkami_openapi/src/response.rs
- samples/petstore/src/main.rs
- samples/worker-with-openapi/src/error.rs
removing previous `Responses::new`.
Before `Responses::enumerated([(code, response); N])` is more generic than `Responses::new(code, response)` and this `new` is useless.
> openapi: repname `Responses::enumerated` into `Responses::new`

- Cargo.toml
- Taskfile.yaml
- benches_rt/async-std/Cargo.toml
- benches_rt/async-std/src/bin/param.rs
- benches_rt/glommio/Cargo.toml
- benches_rt/nio/Cargo.toml
- benches_rt/tokio/Cargo.toml
- benches_rt/vs_actix-web/Cargo.toml
- ohkami/src/lib.rs
- ohkami/src/ws/worker.rs
- ohkami_macros/src/lib.rs
- ohkami_macros/src/worker.rs
- ohkami_macros/src/worker/durable.rs
- samples/test.sh
- samples/worker-bindings/wrangler.toml
- samples/worker-durable-websocket/.cargo/config.toml
- samples/worker-durable-websocket/Cargo.toml
- samples/worker-durable-websocket/package.json
- samples/worker-durable-websocket/src/lib.rs
- samples/worker-durable-websocket/src/room.rs
- samples/worker-durable-websocket/wrangler.toml
Add `ohkami::{DurableObject, #[DurableObject]}`.
They are what I'm trying to update in `worker` crate itself, but the PR is not reviewed for a long time. So this PR ports them into `ohkami`. See https://github.com/cloudflare/workers-rs/pull/675 for detailed background.
> worker: better Durable Object

- README.md
- ohkami/src/fang/builtin/basicauth.rs
- ohkami/src/fang/middleware/util.rs
- ohkami/src/lib.rs
- ohkami_macros/src/worker.rs
- ohkami_openapi/src/paths.rs
- samples/openapi-tags/.gitignore
- samples/openapi-tags/Cargo.toml
- samples/openapi-tags/openapi.json.sample
- samples/openapi-tags/src/main.rs
- samples/petstore/src/main.rs
- samples/readme-openapi/src/main.rs
- samples/streaming/src/main.rs
- samples/test.sh
- samples/worker-with-openapi/src/fang.rs
Support tag in OpenAPI:
*lib.rs*
```rust
mod openapi {
...
/// A fang to set OpenAPI tag for handlers of a `Ohkami`
/// 
/// ## note
/// 
/// * OpenAPI tags are inherited and stacked for child `Ohkami`s (if any).
/// * This is a fang, but introduces NO runtime overhead.
/// 
/// ## example
/// 
/// ```ignore
/// use ohkami::prelude::*;
/// use ohkami::openapi;
/// 
/// #[tokio::main]
/// async fn main() {
///     let users_ohkami = Ohkami::new((
///         openapi::Tag("users"),
///         "/"
///             .GET(list_users),
///             .POST(create_user),
///         "/:id"
///             .GET(get_user_profile),
///     ));
///     
///     Ohkami::new((
///         "/users".By(users_ohkami),
///         
///         // ...
///     )).howl("localhost:5050").await
/// }
/// # …
> openapi: tag

- samples/test.sh
- samples/worker-with-openapi/openapi.json.loggedin.sample
- scripts/workers_openapi.js
By default, `worker_openapi.js` automatically runs `npx wrangler login` and gets cloudflare account name to generate
```json
,
{
"url": "https://{worker-name}.{account-name}.workers.dev",
"description": "production"
}
```
in `openapi.json` if needed.
But this makes an difference between results in local and one in remote CI due to existence of Cloudflare credential, so before we can't make this part contained in `openapi.json.sample` for remote CI without login, while had to temporarily adding it only just before local diff-test for with login.
This PR eliminates that annoying hand process by introducing `--skip-login` option.
Currently local diff test with logged in is temporary, executed only in my ( @kanarus 's ) local env; FIXME to generic way
> chore(openapi): worker_openapi.js: add `--skip-login` option for diff test

- ohkami/src/lib.rs
- `alarm` : not panic with `unimplemented!`, return `worker::Error`. `console_error!` is enough for logging
- `websocket_{message, close, error}` : not call either `console_error!` or `unimplemented!`, just return `Ok(())`. it can be valid Durable Object handling WebSocket.
> fix(worker): improve `DurableObject`'s default method impls

- ohkami/src/typed/header.rs
- ohkami/src/typed/mod.rs
extract specific request header ( currently standard header only )
```rust
use ohkami::prelude::*;
use ohkami::typed::header;
async fn private_handler(
header::Authorization(a): header::Authorization<&str>,
r: Option<header::Referer<&str>>,
) -> String {
println!("Referer: `{r:?}`");
let token = a.strip_prefix("Bearer ")
.expect("expected `Bearer <token>`");
format!("got Authorization: `{token}`")
}
#[tokio::main]
async fn main() {
Ohkami::new((
"/private".GET(private_handler),
)).howl("localhost:5050").await
}
```
> feat: `typed::header`

- ohkami/Cargo.toml
- ohkami/src/x_worker.rs
- ohkami_macros/src/lib.rs
- ohkami_macros/src/worker.rs
- ohkami_macros/src/worker/binding.rs
- samples/worker-bindings/src/lib.rs
Before `#[bindings]` just accept unit struct and collect all bindings of wrangler.toml. But this has a problem: the code itself is difficult to read around bindings because they're defined in implicit fields generated by attribute.
```rust
#[ohkami::bindings]
struct Bindings;
async fn handler(b: Bindings) -> String {
// this `MY_KV` requires readers to check wrangler.toml to understand this code
let data = b.MY_KV.get("data").text().await
.expect("Failed to get data");
//...
}
```
This PR introduces *manual binding* mode of `#[binding]` to resolve it for more readability and potability:
```rust
use ohkami::bindings;
#[bindings]
struct Bindings {
MY_KV: bindings::KV,
}
async fn handler(b: Bindings) -> String {
let data = b.MY_KV.get("data").text().await
.expect("Failed to get data");
//... …
```
> worker: Support manual binding in `#[bindings]`

- ohkami/src/response/into_response.rs
- ohkami/src/response/mod.rs
- ohkami/src/typed/status.rs
- samples/petstore/src/main.rs
`new` will be more expected and intuitive for most Rustaceans.
> rename: `Response::of` -> `Response::new`

- ohkami/src/response/into_response.rs
instead of with `200`.
handlers returning `Response` and `Status` can respond with any HTTP status, so inconsistent documentation will be more avoidable by just empty `openapi::Responses`.
> openapi: make `{Response, Status}::openapi_responses` return empty `Responses`

- ohkami/src/x_lambda.rs
to avoid conflict around static `ROUTER`
releated to https://github.com/ohkami-rs/ohkami/issues/331
> fix: unify `x_lambda::ohkami_service_*` tests into single one

- ohkami/src/request/query.rs
Before, when `request::QueryParams` is constructed from an empty bytes, `QueryParams::iter` returned an iterator that have a single item of an empty string. This is unexpected and This OR fixes it to return empty iterator from empty input.
and add test for it
> fix: `QueryParams::iter`: empty iterator when empty query

- ohkami/src/format/builtin/html.rs
- ohkami/src/format/builtin/json.rs
- ohkami/src/format/builtin/text.rs
- ohkami/src/format/builtin/urlencoded.rs
- ohkami/src/request/from_request.rs
- ohkami/src/response/into_response.rs
Before `IntoBody::into_body` returned `Result<Vec<u8>, _>`, where make any body into owned. But `Response` itself can hold `&'static _` by `Content::Payload({CowSlice})`, so this PR changes the `Vec<u8>` into `Cow<'static, [u8]>` and enables to respond with a static reference.
This doesn't degrade performance in already-owned cases, thanks to Rust's very low cost enum dispatching.
> activate `Cow::Borrowed` via `IntoBody`

- ohkami_macros/src/openapi.rs
- ohkami_openapi/src/paths.rs
Thinking about manual `map_openapi_operation` instead of `#[operation]` like
```rust
use ohkami::handler::IntoHandler;
struct ListUsers;
impl ListUsers {
async fn handle() -> JSON<Vec<User>> {
JSON(vec![])
}
}
impl IntoHandler<ListUsers> for ListUsers {
fn into_handler(self) -> ohkami::handler::Handler {
(Self::handle).into_handler().map_openapi_operation(|mut op| {
op = op
.operationId("list_users")
.description("This doc comment is used for the\n`description` field of OpenAPI document")
.summary("...");
op.override_response_description(200, "List of all users");
op
})
}
}
```
`override_*` methods are unfriendly for this use, while are needed to be the signature ( `fn (&mut Self, ...)` ).
So this PR changes them to `fn (Self, ...) -> Self` to enable to write `map_openapi_operation` by a …
> openapi(operation): replace `override_*` to map signature

- ohkami/src/request/from_request.rs
- ohkami/src/router/final.rs
- ohkami_openapi/src/paths.rs
- ohkami_openapi/src/request.rs
Before any `FromParam` impls of path param types returns `Parameter::{in_path, maybe_in_path}("", ...)` from `openapi_param()`. This is required for name assigning step later, but always `""` is unfriendly. This PR removes it.
> openapi: remove `name` argument of `Parameter::{in_path, maybe_in_path}`

- ohkami/src/fang/handler/into_handler.rs
- ohkami/src/fang/handler/with_local_fangs.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/ohkami/routing.rs
- ohkami/src/request/path.rs
- ohkami/src/router/base.rs
- ohkami/src/router/final.rs
- ohkami/src/router/segments.rs
- ohkami_lib/src/lib.rs
- ohkami_lib/src/map.rs
- ohkami_macros/src/openapi.rs
- ohkami_openapi/src/paths.rs
- ohkami_openapi/src/request.rs
- samples/worker-bindings/src/lib.rs
Before, mismatch of path params at registration like
```rust
// requires 1 path param
async fn hello(name: &str) -> String {
format!("Hello, {name}!")
}
// capture 0 path params
Ohkami::new((
"/hello".GET(hello),
))
```
causes *undefined behavior*, actually ( Ohkami trusted users TOO much that they never write such codes ) .
This PR:
- adds `n_params` to `IntoHandler` and store it in `HandlerSet`.
- updates `base::Router`'s `routes` to hold `HashMap<RouteSegments, TupleMap<Method, HandlerMeta>>`, here `HandlerMeta` stores `n_params`
- updates `base::Router::finalize` to check that each handler's `n_params` doesn't exceeds the number of param segments of corresponded `RouteSegments`. if exceeds, safely panic with friendly message.
The `n_params`s exist only in preparing step, and the check …
> Check the number of required path params

- ohkami_macros/src/openapi.rs
- ohkami_openapi/src/schema.rs
- samples/openapi-schema-enums/Cargo.toml
- samples/openapi-schema-enums/openapi.json
- samples/openapi-schema-enums/openapi.json.sample
- samples/openapi-schema-enums/src/main.rs
- samples/test.sh
Fix
- resolve `#[openapi(component)]` of properties
- specialize simple enum's `Schema` as string enum in OpenAPI
- `#[serde]` intercept: `rename_all` of container's and variant's
and add sample samples/openapi-schema-enums and diff test for it in samples/test.sh
> openapi: Fix #[derive(Schema)] bugs

- ohkami_macros/src/openapi.rs
- samples/openapi-schema-enums/openapi.json
- samples/openapi-schema-enums/openapi.json.sample
- samples/openapi-schema-enums/src/main.rs
- samples/openapi-schema-from-into/Cargo.toml
- samples/openapi-schema-from-into/openapi.json
- samples/openapi-schema-from-into/openapi.json.sample
- samples/openapi-schema-from-into/src/main.rs
- samples/test.sh
When
- `#[serde(into = "...")]`
- `#[serde(from = "...")]`
- `#[serde(try_from = "...")]`
specified, `#[derive(Schema)]` now outputs the partner's schema
> openapi(#[derive(Schema)]): Support intercepting `from`, `into`, `try_into` serde helper attributes

- README.md
- ohkami/src/fang/builtin.rs
- ohkami/src/fang/builtin/enamel.rs
- ohkami/src/fang/builtin/helmet.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/_test_headers.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
- ohkami/src/router/final.rs
- ohkami/src/ws/mod.rs
- ohkami/src/ws/native.rs
- ohkami/src/ws/worker.rs
Add `fang::enamel::{Enamel, CSP, sandbox, src}` for security headers => close #264 
with refactoring around response headers and fix flaky test ( 1 sec diff ) => related to #331
> builtin: security headers

- ohkami/src/fang/middleware/util.rs
- ohkami/src/fang/mod.rs
In
* `FangProc::bite`
* `FangAction::{fore, back}`
stop using `-> impl SendOnNativeFuture<...>` but explicitly write twice with `#[cfg]`s for rust-analyzer's completion.
Currently rust-analyzer can complete `-> Future` methods as `async fn ...` **only when** it returns exactly one of:
* `-> impl Future<Output = T>`
* `-> impl Future<Output = T> + Send`
* `-> impl Future<Output = T> + Send + 'lifetime`
so `-> impl SendOnNativeFuture<T>` prevents his completion...
> DX(fangs): alter `FangProc::bite` `FangAction::{fore, back}` interface to enable rust-analyzer's `async fn ...` completion

- README.md
waiting for https://github.com/the-benchmarker/web-frameworks's issue 8229 to be resovled
> docs(README): temporarily remove `Web Frameworks Benchmark` link

- ohkami/src/fang/builtin/basicauth.rs
- ohkami/src/fang/builtin/context.rs
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/fang/builtin/enamel.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/middleware/mod.rs
- ohkami/src/fang/mod.rs
- ohkami/src/request/context.rs
By mistake, on `rt_worker`, some builtin fangs like `JWT` are not fang when the type param is not `Send + Sync`, which is quite common case, before this PR!
This PR:
- fixes `Send + Sync` to `SendSyncOnNative` in all related parts
- add `*_fang_bound` tests for builtin fangs
> fix(builtin fangs): use `SendSyncOnNative` instead of `Send + Sync` for rt_worker

- ohkami/src/fang/builtin/jwt.rs
for utility from user-defined fangs that internally use `JWT`
> builtin(JWT): add `.get_token_fn()`, `.openapi_security()` getters

- ohkami/src/fang/bound.rs
- ohkami/src/fang/mod.rs
- ohkami/src/util.rs
for utility to develop third party fangs that should be work both on native runtime and rt_worker
> DX: export `SendOnNative`, `SendSyncOnNative` from `utils` and `fang::bound`

- ohkami/src/format/builtin.rs
- ohkami/src/typed/header.rs
- ohkami_lib/src/lib.rs
- ohkami_lib/src/serde_cookie.rs
- ohkami_lib/src/serde_cookie/_test.rs
- ohkami_lib/src/serde_cookie/de.rs
Before it take just `T: FromHeader<'_>` value, requiring user to implement parsing flow from a raw `&str`, as other typed headers. But `Cookie` header value is composed by key-values in format like `name1=value1; name2=value2` and developer's interest is not in this entire string itself. This forced Ohkami users to write similar parsing process by their hands for evenry use of `typed::header::Cookie`s.
So this PR introduces `ohkami_lib::serde_cookie` and enhance `ohkami::typed::header::Cookie` to take `T: Deserialize<'_>`, allowing users to focus on the parsed struct, not on parsing flow.
> enhance: specialize `typed::header::Cookie` with `ohkami_lib::serde_cookie` + `Deserialize`

- ohkami/src/typed/header.rs
Before `Parameter::{in_query, maybe_in_query}` was used by mistake! This PR fixes to `in_cookie`
> fix(openapi): fix `typed::header::Cookie`'s `openapi_inbound`

- ohkami/src/x_worker.rs
- ohkami_macros/src/lib.rs
- ohkami_macros/src/worker.rs
- ohkami_macros/src/worker/binding.rs
Before, in manual binding mode of `#[bindings]`, doc comments for variable bindings like
```rust
#[bindings]
struct Bindings {
/// this is a sample variable binding
MY_VARIABLE: bindings::Var,
}
```
are not shown only for the fields, not in associated consts corresponded to them. This PR improves this DX by copying the doc comments if any to each associated consts.
> Dx(worker): copy var binding doc comments to associated consts

- ohkami/src/ohkami/mod.rs
- ohkami/src/router/final.rs
- ohkami_lib/src/map.rs
- samples/petstore/openapi.json.sample
- samples/petstore/src/main.rs
- samples/realworld/Cargo.toml
- samples/test.sh
- closes https://github.com/ohkami-rs/ohkami/issues/357
- tested by `samples/petstore`'s diff test ( by `samples/test.sh` )
---
Before, for routes like
```rust
Ohkami::new((
"/pets/:petId"
.GET(show_pet_by_id)
.PUT(edit_pet_profile),
"/pets/admin"
.GET(show_pets_detail),
))
```
, `gen_openapi_doc` generates `edit_pet_profile` **twice**, one is to `PUT /pets/:petId` correctly and other is **to `PUT /pets/admin` by bug**.
This is due to searching way in `gen_openapi_doc` that tries to find operations for each registered paths by **all methods**.
So, in this case, it *finds* an operation `edit_pet_profile` when searching `/pets/admin` with `PUT` method, matching to `/pets/:petId` .
This PR fixes this bug by using registered methods information stored in `router::base::Router`'s `routes` …
> fix(openapi): wrong operation generation

- ohkami/src/format/builtin/query.rs
- ohkami/src/typed/header.rs
- ohkami_openapi/src/request.rs
close https://github.com/ohkami-rs/ohkami/issues/391
> rename(openapi): `Parameter::maybe_in_*` -> `Parameter::in_*_optional`

- ohkami_openapi/src/security.rs
fix simply wrong `:"header"` into `:"query"` in `query` and `:"cookie` in `cookie`
> fix(openapi): correct `APIKey::{query, cookie}`'s `apikey_in:"header"`

- ohkami/src/x_worker.rs
- ohkami_macros/src/worker.rs
- ohkami_macros/src/worker/binding.rs
- samples/test.sh
- samples/worker-bindings/Cargo.toml
- samples/worker-bindings/dummy_env_test.js
- samples/worker-bindings/src/lib.rs
- samples/worker-with-global-bindings/.gitignore
- samples/worker-with-global-bindings/Cargo.toml
- samples/worker-with-global-bindings/migrations/0001_schema.sql
- samples/worker-with-global-bindings/openapi.json
- samples/worker-with-global-bindings/package.json
- samples/worker-with-global-bindings/src/lib.rs
- samples/worker-with-global-bindings/wrangler.toml
close https://github.com/ohkami-rs/ohkami/issues/415
tested by
- `samples/worker-bindings` ( add `handle_dummy_env()` and `dummy_env_test.js`  )
- `samples/worker-with-global-bindings` ( new )
( via `samples/test.sh` )
---
Internally, this PR introduces `x_worker::FromEnv` trait for global bindings arg. Basically it just provides `fn from_env(&worker::Env) -> Result<Self>`.
However, the `worker::Env` **does not exist** during openapi generation phase. So `FromEnv` has hidden methods `bindings_meta` and `dummy_env` to work around it. The latter, `dummy_env`, literally creates _**dummy**_ `worker::Env` object in place, depending on metadata from the former `bindings_meta` generated by `#[bindings]`. Dirty hack...
> enhance(worker): Support global bindings arg of `#[worker]`

- ohkami/src/response/into_response.rs
close https://github.com/ohkami-rs/ohkami/issues/417
> enhance(openapi): provide default implementation of `openapi_responses` returning empty `Responses`

- ohkami_openapi/src/response.rs
- samples/petstore/openapi.json.sample
- samples/petstore/src/main.rs
related to: https://github.com/ohkami-rs/ohkami/issues/417
tested by:
- `samples/petstore`'s `createPet` operation ( via `samples/test.sh` )
---
Before `#[operation]`'s description overriding can only overwrite description of already-contained status in the operation's original `openapi::Response`. But:
- this is inconsistent with that `#[operation]`'s `summary` can newly insert `summary` field to the operation.
- will be better if it can newly set any possible statuses of the operation for more flexible documentation.
So this PR enables it.
> enhance(openapi): allow `#[operation]` to newly set status description

- ohkami/src/fang/builtin/context.rs
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/ohkami/routing.rs
- ohkami/src/request/from_request.rs
- ohkami/src/request/mod.rs
- ohkami/src/request/query.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/status.rs
- ohkami/src/session/mod.rs
- ohkami/src/typed/status.rs
- ohkami/src/util.rs
close https://github.com/ohkami-rs/ohkami/issues/408
> enhance(typed): success status with headers

- ohkami/src/util.rs
- avoid printing `file`, `line`, `column` except for `DEBUG!` . they are Ohkami's internal implementations' information and useless for users
- unify header ( `[ohkami:_____]` )'s width for ease of log viewing:
- `[ohkami:WARNS]`
- `[ohkami:ERROR]`
- `[ohkami:DEBUG]`
> enhance(util): improve internal log macros

- ohkami_macros/Cargo.toml
- ohkami_macros/src/util.rs
- ohkami_macros/src/worker.rs
- ohkami_macros/src/worker/binding.rs
- ohkami_macros/src/worker/meta.rs
- ohkami_macros/src/worker/wrangler.rs
- samples/test.sh
- samples/worker-bindings-jsonc/.cargo/config.toml
- samples/worker-bindings-jsonc/Cargo.toml
- samples/worker-bindings-jsonc/src/lib.rs
- samples/worker-bindings-jsonc/wrangler.jsonc
- samples/worker-bindings/Cargo.toml
- samples/worker-bindings/dummy_env_test.js
close https://github.com/ohkami-rs/ohkami/issues/409
> enhance(worker): Support wrangler.jsonc

- README.md
related to
- https://github.com/ohkami-rs/ohkami-templates/pull/43
> docs(worker): say `wrangler.jsonc` instead of `wrangler.toml` in template description

- ohkami/src/fang/middleware/mod.rs
- ohkami/src/fang/mod.rs
- ohkami/src/ohkami/mod.rs
tested by: test `ohkami_is_send_sync_static_on_native` in `ohkami/ohkami/mod.rs`
---
This PR adds `SendSyncOnNative` super traits to `Fangs` `Fangs`, which have been *implicitly* required in other APIs ( like `fang::Context` ) for now.
Additionally, this, especially the latter's `Send`, makes `Ohkami` instance itself `Send` on native environment.
> enhance(fangs): set `SendSyncOnNative + 'static` as super trait of `Fang` `Fangs`

- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
tested by: `*example_with_tcp_listener.rs*` sample code in doc comment of `Ohkami::howl` ( via `task test:doc` )
---
This PR enhances `Ohkami::howl` to be callable with an existing `TcpListener`, not only `ToSocketAddrs`-impl items.
Internally introducing `IntoTcpListener` trait to abstract `ToSocketAddrs`-impl types and `TcpListener` itself together.
This enables for users to configure socket to pass to `Ohkami::howl` e.g. set `SO_REUSEADDR`
> enhance(ohkami): Support howl with an existing `TcpListener`

- examples/Cargo.toml
- examples/hello/Cargo.toml
- examples/multiple-single-threads/Cargo.toml
- examples/multiple-single-threads/src/main.rs
- ohkami/src/ohkami/mod.rs
tested by:
- `examples/multiple-single-threads` ( behavior; interrupt by hand )
- `benches_rt/tokio/bin/param.rs` ( perf; compare `wrk` result with that of `v0.24` branch )
we should add an regression test in future at least for the behavior
---
In some cases, spawning multiple thread each of which runs single-thread async runtime with `SO_REUSEADDR` is more performant than just a multi-thread runtime ( especially when interacting with DB / example: https://github.com/TechEmpower/FrameworkBenchmarks/blob/38c565ebaa900b4db51c0425d11a6619a5615a79/frameworks/Rust/axum/src/server.rs#L109-L130 ) .
Howeveer, before Ohkami ( on other than `rt_glommio` ) has been assumed that only single `Ohkami` instance is running in an application, causing panics when running multiple `Ohkami` instances.
This …
> enhance(ohkami): Support single-thread async runtime on multiple threads

- examples/static_files/public/.env.sample
- examples/static_files/public/index.html
- examples/static_files/public/index.js
- examples/static_files/src/main.rs
- examples/test.sh
- ohkami/Cargo.toml
- ohkami/src/ohkami/dir.rs
- ohkami/src/ohkami/routing.rs
- ohkami/src/router/segments.rs
- ohkami/src/testing/mod.rs
This PR adds test for `.Dir()` by `examples/static_files` ( via `examples/test.sh` ) , with adding `TestResponse::content()` and fixing `RouteSegment::new`'s validation
> chore: test `.Dir()`

- examples/jwt/src/main.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/testing/mod.rs
- samples/realworld/src/_test.rs
instead of returning the `Result`, useless in testing situation, call `.expect("...")` to panic immediately
> enhance(testing): expect `TestResponse::json`'s `serde_json::Result` to be `Ok`

- examples/static_files/src/main.rs
- ohkami/src/header/etag.rs
- ohkami/src/header/mod.rs
- ohkami/src/ohkami/dir.rs
- ohkami/src/ohkami/routing.rs
- ohkami/src/response/headers.rs
- ohkami_lib/src/time.rs
This PR enhances `.Dir()` to support conditional GET based on `If-None-Match`, `If-Modified-Since`.
May needs tests for its behavior ( in `examples/static_files`'s `test` ? )
> enhance(Dir): support conditional fetch

- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
- samples/issue_459/Cargo.toml
- samples/issue_459/README.md
- samples/issue_459/src/main.rs
> cherry-pick #460 into v0.24

- ohkami/src/session/mod.rs
Session timeout very often happens in some clients such as browsers, and logs of them do not help anything in most cases.
Current Ohkami outputs these logs as `WARNS` log, so for browser, prints warning for **almost every** sessions! This will be only annoying in most situation.
This PR changes session timeout logs to be `DEBUG` ones, output only when `DEBUG` feature is activated.
> handle Keep-Alive timeout log as `DEBUG`, not `WARNING`

- ohkami/src/config.rs
- ohkami/src/session/mod.rs
- fix default websocket timeout ( was malformed to `42` at some time in past... ) to `1 * 60 * 60`
- fix default keep-alive timeout from `42` to `30` for better behavior in more cases
> fix(session): revise default timeout config

- .github/workflows/CI.yml
in order to maximize cache hit from the next run
> chore(CI): cache sccache directory after the most large task

- examples/hello/src/main.rs
- examples/html_layout/src/main.rs
- ohkami/src/fang/builtin/basicauth.rs
- ohkami/src/fang/builtin/cors.rs
- ohkami/src/fang/builtin/enamel.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/handler/mod.rs
- ohkami/src/header/append.rs
- ohkami/src/header/setcookie.rs
- ohkami/src/ohkami/dir.rs
- ohkami/src/request/_test_headers.rs
- ohkami/src/request/from_request.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/mod.rs
- ohkami/src/response/_test.rs
- ohkami/src/response/_test_headers.rs
- ohkami/src/response/headers.rs
- ohkami/src/response/mod.rs
- ohkami/src/session/mod.rs
- ohkami/src/testing/mod.rs
- ohkami/src/typed/header.rs
- ohkami/src/typed/status.rs
- ohkami/src/ws/mod.rs
- ohkami/src/ws/native.rs
- samples/realworld/src/fangs.rs
- samples/realworld/src/handlers.rs
- samples/worker-with-openapi/src/fang.rs
This PR partially resolves #376 around headers as #485 did around fang/format: rename all `.PascalCase()` header method names into `.snake_case()`.
Considering users' rewriting cost, this remains `.PascalCase` methods with `#[deprecated = "Use snake_case method instead"]`. They will be removed in v0.25.
> rename(headers): follow Rust's naming convention

- ohkami/src/fang/builtin/basicauth.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/handler/into_handler.rs
- ohkami/src/router/final.rs
- ohkami_macros/src/openapi.rs
- ohkami_openapi/src/document.rs
- ohkami_openapi/src/lib.rs
- ohkami_openapi/src/paths.rs
- ohkami_openapi/src/schema.rs
- ohkami_openapi/src/security.rs
- samples/worker-with-openapi/src/fang.rs
following to
- https://github.com/ohkami-rs/ohkami/pull/485
- https://github.com/ohkami-rs/ohkami/pull/487
This PR partially resolves
- #376 
around `openapi` API, and this is the last piece of them: close #376
> rename(openapi): follow Rust's naming convention

- README.md
- examples/quick_start/src/main.rs
- examples/websocket/src/main.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/builtin/timeout.rs
- ohkami/src/fang/handler/into_handler.rs
- ohkami/src/format/builtin.rs
- ohkami/src/format/builtin/multipart.rs
- ohkami/src/format/builtin/path.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/from_request.rs
- ohkami_openapi/src/lib.rs
- samples/openapi-schema-enums/openapi.json.sample
- samples/openapi-schema-from-into/openapi.json.sample
- samples/openapi-tags/openapi.json.sample
- samples/openapi-tags/src/main.rs
- samples/petstore/openapi.json.sample
- samples/petstore/src/main.rs
- samples/realworld/src/handlers/articles.rs
- samples/realworld/src/handlers/profiles.rs
- samples/worker-durable-websocket/src/lib.rs
- samples/worker-with-global-bindings/openapi.json
- samples/worker-with-global-bindings/src/lib.rs
- samples/worker-with-openapi/openapi.json.loggedin.sample
- samples/worker-with-openapi/openapi.json.sample
- samples/worker-with-openapi/src/lib.rs
- close https://github.com/ohkami-rs/ohkami/issues/458
Current
```rust
async fn handler(id: &str, Json(body): Json<Body>) -> ...
```
style depends on the **implicit** rule that the first argument of a handler represents path parameters if its type doesn't implement `FromRequest` trait.
This will be **not intuitive** for most people, at least than explicit `Path(param): Path<T>` style:
```rust
async fn handler(Path(id): Path<&str>, Json(body): Json<Body>) -> ...
```
This PR **breakingly** introduces the `Path<T>` replacing with current implicit path params system.
> feat: introduce `Path<T>` and obsolete current implicit path params

- ohkami/Cargo.toml
- ohkami/src/handle/param.rs
- ohkami_openapi/Cargo.toml
- ohkami_openapi/src/lib.rs
> enhance(handle): impl `FromParam` for `Uuid` by default

- README.md
- ohkami_macros/src/lib.rs
> docs: improve `#[worker]` docs and README's `rt_worker` description

- ohkami/src/fang/handler/into_handler.rs
- ohkami/src/fang/handler/with_local_fangs.rs
Current `IntoHandler` error message is like:
```txt
error[E0277]: the trait bound `fn(String) -> ... {h0}: IntoHandler<_>` is not satisfied
--> ohkami/src/fang/handler/into_handler.rs:319:50
|
319 |             $( let _ = IntoHandler::into_handler($function); )*
|                        ------------------------- ^^^^^^^^^ unsatisfied trait bound
|                        |
|                        required by a bound introduced by this call
...
323 |     assert_handlers! { h0 h1 h2 h3 h4 }
|     ----------------------------------- in this macro invocation
|
= help: the trait `IntoHandler<_>` is not implemented for fn item `fn(String) -> impl Future<Output = &str> {h0}`
= help: the following other types implement trait `IntoHandler<T>`:
`(F1, F2, F3, F4, H)` implements `IntoHandler<(F1, F2, …
```
> dx: put `#[diagnostic::do_not_recommend]` for local fangs' `IntoHandler` impls

- ohkami_openapi/src/lib.rs
- close https://github.com/ohkami-rs/ohkami/issues/407
> docs(openapi): documentation for `Schema` trait

- Taskfile.yaml
- ohkami/Cargo.toml
after
- https://github.com/ohkami-rs/ohkami/pull/495
`nio` v0.0.2 is published and it compiles
> chore(CI): restore `rt_nio` checks/tests

- examples/static_files/src/main.rs
- ohkami/src/ohkami/dir.rs
- ohkami/src/ohkami/routing.rs
- close https://github.com/ohkami-rs/ohkami/issues/518
- tested by examples/static_files's `test_omit_dot_html` and `test_omit_html` (via examples/test.sh by CI)
(just in case: `\.?ext` in the PR title is just for clear description of the behavior, not meaning use of regex crate)
> fix(Mount): `omit_extension`'s doc and behavior to accept both `\.?ext`

- README.md
- examples/websocket/src/main.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/session/mod.rs
This PR:
- introduce `__rt__::accept` function to catch the runtime crates' difference of `TcpListener::accept` result type within `__rt__` module
- introduces an internal unified `howl_core` method and make `howl` and `howls` wrappers of `howl_core`
It achieves:
- reorganize and make clear the logic of `howl` and `howls`
- eliminates duplicate codes between `howl` and `howls` impl
> refactor(Ohkami): reorganize `howl` and `howls`

- README.md
- ohkami/src/fang/builtin.rs
- ohkami/src/fang/builtin/csrf.rs
- ohkami/src/request/method.rs
- ohkami/src/testing/mod.rs
- close https://github.com/ohkami-rs/ohkami/issues/521
> feat(fang): Add builtin CSRF protaction fang

- ohkami/src/request/_test_parse.rs
- ohkami/src/request/headers.rs
- ohkami/src/request/path.rs
- ohkami/src/request/query.rs
- close https://github.com/ohkami-rs/ohkami/issues/540
- breaking: remove `AsRef` and `Deref` impl for `request::Path`
- add: `request::Path::bytes(&self) -> &[u8]` ( non-str version of `request::Path::str` )
> fix(request): avoid panic in str conversion

- ohkami/Cargo.toml
- ohkami/src/fang/bound.rs
- ohkami/src/fang/builtin/basicauth.rs
- ohkami/src/fang/builtin/context.rs
- ohkami/src/fang/builtin/jwt.rs
- ohkami/src/fang/handler/into_handler.rs
- ohkami/src/fang/handler/mod.rs
- ohkami/src/fang/middleware/mod.rs
- ohkami/src/fang/middleware/util.rs
- ohkami/src/fang/mod.rs
- ohkami/src/lib.rs
- ohkami/src/ohkami/_test.rs
- ohkami/src/ohkami/mod.rs
- ohkami/src/request/context.rs
- ohkami/src/request/query.rs
- ohkami/src/util.rs
- samples/issue_550_glommio/Cargo.toml
- samples/issue_550_glommio/README.md
- samples/issue_550_glommio/src/main.rs
- samples/test.sh
- close #550 
- tested by:
- samples/issue_550_glommio (via samples/test.sh by CI)
- ohkami::fang::handler::into_handler::handler_args test (via CI)
---
This PR adds `__rt_threaded__` internal feature flag and changes fang::bound to:
- `SendSyncOnNative` -> `SendSyncOnThreaded`
- `SendOnNative` -> `SendOnThreaded`
- `SendOnNativeFuture` -> `SendOnThreadedFuture`
to correctly handle thread-per-core async runtimes including `glommio`: `__rt_threaded__` is activated by
- `rt_tokio`
- `rt_smol`
- `rt_nio`
- `rt_lambda`
and not activated by
- `rt_glommio`
- `rt_worker`
Additionally, removing an wrong debug assertion in `ohkami::sync::CtrlC::new`: `assert_eq!(index, WAKERS.read().unwrap().len());`.
(There just the amount number of them matters, not the index order. This assertion will cause …
> fix(fangs): correctly handle thread-per-core runtime like glommio

- ohkami_macros/src/worker.rs
Currently `samples/worker-durable-websocket` fails to compile:
```stdout
cargo check
Compiling ohkami_macros v0.24.1 (/home/kanarus/projects/ohkami-rs/ohkami/ohkami_macros)
Checking ohkami v0.24.1 (/home/kanarus/projects/ohkami-rs/ohkami/ohkami)
Checking worker-with-openapi v0.1.0 (/home/kanarus/projects/ohkami-rs/ohkami/samples/worker-durable-websocket)
error[E0433]: failed to resolve: could not find `wasm_bindgen` in the list of imported crates
--> src/room.rs:7:1
|
7 | #[DurableObject]
| ^^^^^^^^^^^^^^^^ could not find `wasm_bindgen` in the list of imported crates
|
= note: this error originates in the attribute macro `::ohkami::wasm_bindgen::prelude::wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
error: cannot find attribute `wasm_bindgen` in this scope …
```
> fix(worker): `#[wasm_bindgen]` handling in `#[DurableObject]`

- ohkami/src/fang/builtin/csrf.rs
ref:
- https://github.com/ohkami-rs/ohkami/security/code-scanning/7
- https://github.com/ohkami-rs/ohkami/security/code-scanning/6
- https://github.com/ohkami-rs/ohkami/security/code-scanning/5
- https://github.com/ohkami-rs/ohkami/security/code-scanning/4
- https://github.com/ohkami-rs/ohkami/security/code-scanning/3
> security: avoid containing `origin` in panic messages

- Cargo.toml
- README.md
- Taskfile.yaml
- benches_rt/compio/Cargo.toml
- benches_rt/compio/src/bin/param.rs
- ohkami/Cargo.toml
- ohkami/src/lib.rs
I probably should've opened an issue first, but the change is quite simple so I decided to just implement and played around with it. Feel free to not merge if it's not suitable.
This adds support for the [`compio`](https://github.com/compio-rs/compio) runtime, another thread per core runtime that supports macOS, Linux and Windows. The API is similar to that of `monoio` and they do provide a `futures` compat layer. It same problem with Ctrl+C as `monoio` stated in #564. However, running the same benchmark as you did `564` the performance seems to be lower that other runtimes.
> feat: add support for compio runtime
