ohkami-rs/ohkami

examples/realworld/src/handlers/articles.rs, examples/realworld/src/handlers/profiles.rs, examples/realworld/src/handlers/tags.rs, examples/realworld/src/handlers/user.rs, examples/realworld/src/handlers/users.rs, examples/realworld/src/models.rs, ohkami/Cargo.toml, ohkami/src/layer1_req_res/response/mod.rs, ohkami/src/lib.rs, ohkami/src/x_utils/mod.rs, ohkami/src/x_utils/status_as_type.rs, ohkami_macros/src/components.rs, ohkami_macros/src/lib.rs, ohkami_macros/src/payload.rs, ohkami_macros/src/query.rs, ohkami_macros/src/response.rs
- add `utils::typed`
- add `#[Response(JSON)]` for utility for using `typed` with json
=> Update around request response 2024 01 12

examples/realworld/.env, examples/realworld/Cargo.toml, examples/realworld/src/config.rs, examples/realworld/src/errors.rs, examples/realworld/src/handlers/articles.rs, examples/realworld/src/handlers/user.rs, examples/realworld/src/handlers/users.rs, examples/realworld/src/models.rs, ohkami/src/layer0_lib/base64.rs, ohkami/src/layer0_lib/mod.rs, ohkami/src/lib.rs, ohkami_macros/src/components.rs, ohkami_macros/src/lib.rs, ohkami_macros/src/payload.rs, ohkami_macros/src/response.rs
- Add `#[ResponseBody(JSONS)]` ( `#[ResponseBody(JSON)] + #[derive(Serialize)]` )
- Add `#[Payload(JSOND)]` ( `#[Payload(JSON)] + #[derive(Deserialize)]` )
- Add `utils::base64`
=> Add ResponseBody(JSONS), Payload(JSOND)

examples/realworld/src/errors.rs, ohkami/Cargo.toml, ohkami/src/layer1_req_res/mod.rs, ohkami/src/layer1_req_res/response/into_response.rs, ohkami/src/layer1_req_res/response/mod.rs, ohkami/src/layer2_fang_handler/handler/handlers.rs, ohkami/src/layer2_fang_handler/handler/into_handler.rs, ohkami/src/layer3_router/mod.rs, ohkami/src/lib.rs, ohkami/src/x_testing/_test.rs, ohkami/src/x_utils/into_response_builtin.rs, ohkami/src/x_utils/jwt.rs, ohkami/src/x_utils/mod.rs, ohkami/src/x_utils/status_as_type.rs, ohkami_macros/src/response.rs
- Fix `impl ResponseBody` builtin: `Into<Cow>` -> `&'static str`,`String`,`&'_ String`
- Add `impl IntoResponse` builtin: `&'static str`,`String`,`&'_ String`
=> Update around request response 2024 01 13

.github/workflows/check.yml, README.md, benches/Cargo.toml, examples/Cargo.toml, ohkami/Cargo.toml
We have to assure the buildablity without `DEBUG` feature
=> Fix workflows

examples/form/src/main.rs, examples/hello/src/main.rs, examples/quick_start/src/main.rs, examples/realworld/src/handlers.rs, examples/realworld/src/main.rs, ohkami/Cargo.toml, ohkami/src/fang/builtin/jwt.rs, ohkami/src/fang/fangs.rs, ohkami/src/fang/mod.rs, ohkami/src/ohkami/build.rs, ohkami/src/ohkami/howl.rs, ohkami/src/ohkami/mod.rs, ohkami/src/ohkami/router/_test.rs, ohkami/src/ohkami/router/radix.rs, ohkami/src/ohkami/router/trie.rs, ohkami/src/request/mod.rs, ohkami/src/request/store.rs, ohkami/src/response/_test.rs, ohkami/src/response/mod.rs, ohkami/src/testing/mod.rs, ohkami/src/utils/mod.rs, ohkami/src/utils/time.rs, ohkami_lib/Cargo.toml, ohkami_lib/src/lib.rs, ohkami_lib/src/time.rs
- Add `Ohkami::howl_with` and *global fang* system, where users can register some fangs to call them for every request regardless of its path
- Fix bug in fang registration ( and update test case for that )
=> Global fangs

README.md, ohkami/Cargo.toml, ohkami/src/ohkami/mod.rs, ohkami/src/ohkami/router/_test.rs, ohkami/src/testing/mod.rs, ohkami_macros/Cargo.toml, ohkami_macros/src/lib.rs
- Add `Testing::oneshot_with(&self, global_fangs, req)`
- Add test cases using `oneshot_with`
=> Add testing oneshot with

ohkami/src/fang/fangs.rs, ohkami/src/fang/mod.rs, ohkami/src/lib.rs
=> refactor fang some & publicate `Fangs` via `__internal__`

examples/Cargo.toml, examples/derive_from_request/Cargo.toml, examples/derive_from_request/src/main.rs, ohkami/Cargo.toml, ohkami/src/lib.rs, ohkami_macros/Cargo.toml, ohkami_macros/src/from_request.rs, ohkami_macros/src/lib.rs
for util in ohkami-openapi use
=> Add derive from request

examples/Cargo.toml, examples/static_files/Cargo.toml, examples/static_files/public/about.html, examples/static_files/public/blog/first.html, examples/static_files/public/blog/index.html, examples/static_files/public/blog/second.html, examples/static_files/public/index.html, examples/static_files/src/main.rs, ohkami/Cargo.toml, ohkami/src/builtin/payload/json.rs, ohkami/src/builtin/payload/text.rs, ohkami/src/builtin/payload/urlencoded.rs, ohkami/src/handler/handlers.rs, ohkami/src/handler/into_handler.rs, ohkami/src/handler/mod.rs, ohkami/src/ohkami/build.rs, ohkami/src/request/mod.rs, ohkami/src/typed/payload.rs, ohkami/src/typed/status.rs, ohkami_lib/Cargo.toml, ohkami_lib/src/lib.rs, ohkami_lib/src/mime.rs
Add `Route::Dir` for static directory serving
=> Add route dir

ohkami/Cargo.toml, ohkami/src/request/_test_headers.rs, ohkami/src/request/headers.rs, ohkami/src/request/mod.rs, ohkami/src/response/_test_headers.rs, ohkami/src/response/headers.rs, ohkami/src/response/mod.rs, ohkami_lib/src/slice.rs
& Remove `#[cfg(feature = "custom-header")]`
=> Add tests for headers

examples/hello/src/main.rs, ohkami/Cargo.toml, ohkami/src/request/_test_headers.rs, ohkami/src/request/headers.rs, ohkami/src/request/mod.rs, ohkami/src/request/path.rs, ohkami/src/session/mod.rs, ohkami/src/testing/mod.rs
Correctly return errors in parsing unexpected requests
=> Improve request parsing

README.md, ohkami/Cargo.toml, ohkami/src/lib.rs, ohkami/src/request/from_request.rs, ohkami_macros/Cargo.toml, ohkami_macros/src/lib.rs, ohkami_macros/src/worker.rs
Add `#[bindings]` that automatically read bindings in user's `wrangler.toml` and bind them as fields of a Rust struct
=> Add bindings attribute

benches/Cargo.toml, examples/Cargo.toml, examples/form/src/main.rs, examples/realworld/src/config.rs, examples/realworld/src/models.rs, examples/realworld/src/models/response.rs, ohkami/Cargo.toml, ohkami/src/builtin/fang.rs, ohkami/src/builtin/fang/jwt.rs, ohkami/src/builtin/mod.rs, ohkami/src/builtin/payload/multipart.rs
and bump version for breaking changes
=> introduce `JWTToken` & export from `builtin::item` together with `File`

ohkami/src/builtin/fang/jwt.rs
- Add `JWT::get_token_by` customizer
- Fix `JWT::verified` to use `utils::unix_timestamp` instead of SystemTime directly ( to support use on `rt_worker` )
- Fix `exp` verifying: to use `unwrap_or(u64::MAX)` instead of `unwrap_or_default` ( which is equivalent to `unwrap_or(0)` )
=> Fix & Update `builtin::utils::JWT`

ohkami/src/builtin/fang/cors.rs, ohkami/src/fangs/handler/into_handler.rs, ohkami/src/lib.rs, ohkami/src/ohkami/build.rs, ohkami/src/ohkami/router/trie.rs, ohkami/src/request/from_request.rs, ohkami/src/request/memory.rs, ohkami/src/request/mod.rs, ohkami/src/response/headers.rs, ohkami/src/response/mod.rs, ohkami/src/session/mod.rs, ohkami/src/typed/payload.rs, ohkami/src/typed/status.rs
Replace all & Use `console_warn!` (instead of `console_error!`) on `rt_worker`
=> `log_error!` → `warning!`

benches/src/bin/param.rs, ohkami/src/fangs/handler/into_handler.rs, ohkami/src/fangs/mod.rs, ohkami/src/lib.rs, ohkami/src/request/from_request.rs, ohkami/src/request/memory.rs, ohkami/src/response/headers.rs, ohkami/src/session/mod.rs, ohkami/src/typed/status.rs
- tune `#[inline]`s
- fix bug in response header's size tracking
=> Performance tuning

benches/benches/itoa.rs, ohkami_lib/src/num.rs
100x faster than `usize::to_string`
=> perf: more optimized `itoa`

benches/benches/itoa.rs
fix https://github.com/ohkami-rs/ohkami/commit/8fcc4f67f888e6a3134fbaba03862e05d7e07695#r143970218
> 🤔
> 
> It seems to neglect the fact that the process specified in bench is executed repeatedly. The size of buf is increased each time the contents of bench are executed.
---
*benches/benches/itoa.rs*
```diff
let mut buf = String::with_capacity(v.len() * 21);
b.iter(|| {
+    /*
+        reuse the same buffer and avoid redundant allocation during each iter
+
+        - `.as_mut_vec().set_len(0)` is very cheap at the cost
+        - `buf.{push, push_str}` just do `ptr::write` and `set_len` due to the enough capacity,
+          whitch means following `c_lib` overwrites existing bytes
+        - `Drop` impls of overwritten bytes are never called but this is not a problem
+          because …
```
=> fix itoa bench: reuse the same buffer and avoid redundant allocation during each iter

Cargo.toml, README.md, Taskfile.yaml, benches/src/bin/hello.rs, benches_glommio/Cargo.toml, benches_glommio/src/bin/param.rs, ohkami/Cargo.toml, ohkami/src/fang/builtin.rs, ohkami/src/fang/builtin/timeout.rs, ohkami/src/fang/mod.rs, ohkami/src/header/map.rs, ohkami/src/lib.rs, ohkami/src/ohkami/mod.rs, ohkami/src/request/_test_headers.rs, ohkami/src/request/_test_parse.rs, ohkami/src/request/headers.rs, ohkami/src/request/memory.rs, ohkami/src/request/method.rs, ohkami/src/request/mod.rs, ohkami/src/request/path.rs, ohkami/src/request/queries.rs, ohkami/src/request/query.rs, ohkami/src/response/content.rs, ohkami/src/response/headers.rs, ohkami/src/response/mod.rs, ohkami/src/response/status.rs, ohkami/src/session/mod.rs, ohkami/src/ws/connection.rs, ohkami/src/ws/mod.rs
closes https://github.com/ohkami-rs/ohkami/issues/251
---
> Glommio is a thread-per-core crate that makes writing highly parallel asynchronous applications in a thread-per-core architecture easier for rustaceans.
https://github.com/DataDog/glommio
=> fea: add `"rt_glommio"`

.github/workflows/auto_approve.yml, README.md, Taskfile.yaml, benches/Cargo.toml, benches_rt/tokio/Cargo.toml, ohkami/Cargo.toml, ohkami/src/lib.rs, ohkami/src/ohkami/mod.rs, ohkami_lib/Cargo.toml, ohkami_lib/src/lib.rs, ohkami_lib/src/signal.rs
closes https://github.com/ohkami-rs/ohkami/issues/235
---
- Perform graceful shutdown on native runtime by default
- Remove `graceful` feature flag
This is breaking change, bumps v0.20 -> v0.21
=> feat: graceful shutdown on all native runtime

ohkami/src/ws/worker.rs
I found `close`ing cloned `worker::WebSocket` doesn't affect the original one. So this PR fixes `ws/worker.rs` to avoid cloning `ws` itself and wrap it by `Rc`.
=> fix: ws on rt_worker: wrap `ws` in `Rc` instead of clone `ws` itself

.github/workflows/CI.yml
for actions cache of PRs to `v*` branch
=> chore(CI): add `v*` to `on.push.branches`

ohkami/src/ohkami/mod.rs
Before `WaitGroup` performed subtraction in `fn done(&self)`, but this is **never** called if a **unexpected panic** has occurred outside of `catch_unwind` of `router.handle`. It means `WaitGroup::poll` always returns `Pending` and Ohkami **eternally** runs the graceful shutdown process.
This PR resolves it by delegating the subtraction into **`Drop` impl** and alter `done` into `fn done(self) {/* just drop */}`. In this implementation, `drop` is **definitely** called even if `done` is not called due to some unexpected panic, and it surely subtracts the count with no problem.
=> fix(native): perform `WaitGroup`'s subtraction in `Drop` impl for panic safety

scripts/workers_openapi.js
=> add wasm-pack installation part in scripts/workers_openapi.js

Cargo.toml, ohkami/Cargo.toml, ohkami/src/sse/mod.rs, ohkami/src/ws/native.rs, ohkami_lib/Cargo.toml, ohkami_macros/Cargo.toml, ohkami_openapi/Cargo.toml
control `[package]` keys at workspace root Cargo.toml except for `name`, `description`, `documentation`
=> chore(workspace)

ohkami/src/request/mod.rs, ohkami/src/util.rs
based on `CF-Connecting-IP` header ( https://developers.cloudflare.com/fundamentals/reference/http-request-headers/ )
=> feat: `Request.ip` on rt_worker

README.md
=> doc: README

ohkami_lib/Cargo.toml
already unused feature and dependencies
=> chore(lib): remove `signal`

ohkami/src/fang/handler/into_handler.rs, samples/openapi-tags/openapi.json.sample, samples/readme-openapi/openapi.json.sample, samples/streaming/openapi.json.sample, samples/worker-with-openapi/openapi.json.loggedin.sample, samples/worker-with-openapi/openapi.json.sample
closes https://github.com/ohkami-rs/ohkami/issues/361
=> openapi: refer to `any::type_name::<F>` in `IntoHandler` and automatically set default `operationId`

ohkami_macros/src/lib.rs
that it's not an actual problem and `Queue` binding does work
=> docs: add note for warnings of `Queue` binding in `wrangler dev`

ohkami/src/typed/status.rs
utility for handlers returning a typed redirect ( e.g. `typed::status::Found` ) to set, like, `Set-Cookie` header without *flatten* the type into plane `Response`
=> enhance: add `with_headers` method of `typed::status`'s redirect types

ohkami/src/fang/handler/into_handler.rs
Before this logic was wrong: not handled generics of type. For example, handler like
```rust
async fn handler<R: Repository>(
Context(r): Context<'_, R>,
) {}
```
was detected as `R>` by the bug.
This PR fixes it and now above handler is detected as `handler` as expected.
=> fix(openapi): fix logic to getting type identifier in `into_handler::with_default_operation_id`

ohkami/src/format/builtin/html.rs, ohkami/src/format/builtin/json.rs, ohkami/src/format/builtin/multipart.rs, ohkami/src/format/builtin/query.rs, ohkami/src/format/builtin/text.rs, ohkami/src/format/builtin/urlencoded.rs
close https://github.com/ohkami-rs/ohkami/issues/389
=> docs(biultin): add detailed document for builtin formats

ohkami/src/x_worker.rs, ohkami_macros/src/worker.rs, ohkami_macros/src/worker/binding.rs
close https://github.com/ohkami-rs/ohkami/issues/421
tested by: `samples/worker-bindings/dummy_env.js` ( via `samples/test.sh` )
=> refactor(worker): use `Option<&'static str>` instead of unclear string convention

ohkami/src/session/mod.rs
I’d like to propose a change to our session management. In our current implementation, a single, upfront timeout is applied to the entire session, which means that in case of sporadic and continuous activity (such as intermittent comments in an SSE stream) will end up in a premature timeout. This can especially be problematic for long-running streams over SSE, where we want the connection to persist as long as there is some minimal activity like periodic comments or keep-alive pings. 
Also, it seems like a good feature idea to introduce a new sse API method to insert regular keep-alive comments at configurable intervals and timeout. This ensures that even during periods of little or no activity (common in sse streams), the connection remains open.
=> Use per-read timeouts for improved keepalive handling in session

README.md, ohkami/src/ohkami/mod.rs
as `https` to `http`, `wss` to `ws`
=> rename(Ohkami): `howl_tls` to `howls`

ohkami/src/config.rs, ohkami/src/session/mod.rs
=> fix(session): revise default timeout config

README.md
=> docs: specify runtime versions

README.md
close https://github.com/ohkami-rs/ohkami/issues/410
=> docs: mention `openapi::Tag` in README

ohkami/src/lib.rs, ohkami/src/ohkami/mod.rs, ohkami/src/response/mod.rs
- close https://github.com/ohkami-rs/ohkami/issues/524
=> docs: `#[cfg_attr(docsrs, doc(cfg(feature = "...")))]`

benches/benches/request_headers.rs, benches/benches/response_headers.rs, benches_rt/tokio/src/bin/headers.rs, ohkami/src/header/map.rs, ohkami/src/header/mod.rs, ohkami/src/request/headers.rs, ohkami/src/request/mod.rs, ohkami/src/response/headers.rs
with updating tests and {request, response}::headers for the change
=> refactor(header): improve `IndexMap` implementation (into `ByteArrayMap`) and fix benches

ohkami/src/testing/mod.rs
```rust
pub trait Testing {
fn test(self) -> TestingOhkami;
}
```
to
```rust
pub trait Tester {
fn test(self) -> TestOhkami;
}
```
=> rename(testing): `Testing` to `Tester`, `TestingOhkami` to `TestOhkami`

samples/realworld/Cargo.toml
- https://github.com/ohkami-rs/ohkami/security/dependabot/1
=> chore(samples): update dependencies
